### ISSUE TITLE
editor kill ring toggle

### ISSUE THREAD

**Issue by FishoFire** [nebulaOW/genji-framework#19]
Sometimes a circle may be slightly bigger or smaller then it appears, but not for everyone and not always. Sometimes fixed on leaving and joining again.

cp 29 from 98e27 > walking off box sometimes resets you and sometimes not, even if you always go the same way.
cp 13 from A7EQ7 > the circle is bigger then it appears.

**Comment by nebulaOW** [comment]
renamed this issue after research and discussion

**Comment by nebulaOW** [comment]
out of scope
